language: node_js
node_js:
- '0.10'
after_success:
- test "$TRAVIS_REPO_SLUG" == "taylor1791/promissory-arbiter" && test "$TRAVIS_PULL_REQUEST"
  == "false" && test "$TRAVIS_BRANCH" == "master" && bash scripts/deploy-docs.sh
env:
  global:
  - secure: nVb45Rd6Fc40d5bqSzXlVbcVNKaVaR5I794qETdoRfBWHtvmmscdieuuXOofpPFt+IsV5lpq0frPCUjt4cNP8RgrCG2Uinq+fVGt7NGY/uNbl5yP1Xk9D5BcNroFn50+lqt8SvEQt2xdS0FdIhXWZWWTpWteJjd/0GxSFdLwzfVdHQcTh/SjLAvSM0k1N3V1/9rYKczywx/FfJzhavWt6QrloLiswjcHVGJ60VLmMhby1RrIAx17qzoUkwSzbMJ9ngq/HxZKr/M1/RSTqiRxra3t268Lr5XWxGGNb4xj8/zPGkpmglFQoJXT+GnAsP0G2Wp9oiWsHwnyNTv9QC1+LzQrJReB5HFy8H5dj7IRYmeYP8cvY8lt6olAilOX8rihCUsfLhHNu0G8edgYIQ4s2z83skSj7Yg/2qw/XAkAMWcV4Fx7cdY9IyawCzvei5XrOJ22eKzFotmZmtlLKWtsYdXc9F4zxzYGr3pvfClk8eDL/cqHz0VIvKhKuSAKLqdKB96ieMHDjvUbZt1c46Dt+QUqlDVNkjjIftDGeoLXPNWqzOVeDxL3JL6+LCzKi4mZ5hqTmeY9exuREgyo8xEO5xtRKa0LJN52x1XocycbTO8K1aBxKyCpdKcV7qYJIQsTJIz/8vgOzpiAt2jZq8jWRcN3qwYHGhW+ruXbizYcoXE=
